### PR TITLE
Remove min-dom from production deps

### PR DESCRIPTION
**Pull request by barmac**
### Proposed Changes

There is only a single place we use `min-dom` in the production code of this library. In that place, we are certain that the element exists so we don't need null-safety that min-dom's `closest` provides. Thus, I suggest we use DOM `closest` directly, and use `min-dom` utilities in the tests only.

### Checklist

To ensure you provided everything we need to look at your PR:

* [x] **Brief textual description** of the changes present
* [ ] **Visual demo** attached
* [ ] **Steps to try out** present, i.e. [using the `@bpmn-io/sr` tool](https://github.com/bpmn-io/sr)
* [ ] Related issue linked via `Closes {LINK_TO_ISSUE}` or `Related to {LINK_TO_ISSUE}`

### CODE REVIEW

**Comment by nikku** [comment]
If you ask me I'd stick to `min-dom` for DOM operations, as a pattern. 

It is cheap (2kb), and will be deduplicated. The alternative is that we start to use actual element APIs consistently.

**Comment by barmac** [comment]
It is cheap, I agree, but this time it causes headache due to v4->v5 migration. Also, the value provided in this specific library for the production code is minimal. So the only reason we'd keep it is for the sake of consistency.

**Comment by barmac** [comment]
I've added this PR to our weekly for a team discussion. I think we can learn something out of this.

**Comment by barmac** [comment]
Closing this for now. We can reconsider later.

**Pull request closed without merging**
